version: 0.2
phases:
  install:
    commands:
      - pip install cmake
      - pip install pandas
      - pip install beautifulsoup4
      - pip install fastparquet
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml