version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - sudo /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - export PATH="/usr/local/bin:$PATH"
      - brew install cmake
      - pip install -r requirements.txt
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template-file template-export.yml
artifacts:
  files:
    - template-export.yml